// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: payment.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *PaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PaymentsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentsSummaryRequest) Reset() {
	*x = PaymentsSummaryRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentsSummaryRequest) ProtoMessage() {}

func (x *PaymentsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentsSummaryRequest.ProtoReflect.Descriptor instead.
func (*PaymentsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentsSummaryRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PaymentsSummaryRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ProcessorSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests int64                  `protobuf:"varint,1,opt,name=totalRequests,proto3" json:"totalRequests,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorSummary) Reset() {
	*x = ProcessorSummary{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorSummary) ProtoMessage() {}

func (x *ProcessorSummary) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorSummary.ProtoReflect.Descriptor instead.
func (*ProcessorSummary) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessorSummary) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ProcessorSummary) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type PaymentsSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Default       *ProcessorSummary      `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Fallback      *ProcessorSummary      `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentsSummaryResponse) Reset() {
	*x = PaymentsSummaryResponse{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentsSummaryResponse) ProtoMessage() {}

func (x *PaymentsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentsSummaryResponse.ProtoReflect.Descriptor instead.
func (*PaymentsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentsSummaryResponse) GetDefault() *ProcessorSummary {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *PaymentsSummaryResponse) GetFallback() *ProcessorSummary {
	if x != nil {
		return x.Fallback
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\n" +
	"rinha_2025\x1a1internal/third_party/google/api/annotations.proto\"N\n" +
	"\x0ePaymentRequest\x12$\n" +
	"\rcorrelationId\x18\x01 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"?\n" +
	"\x0fPaymentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x16PaymentsSummaryRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"Z\n" +
	"\x10ProcessorSummary\x12$\n" +
	"\rtotalRequests\x18\x01 \x01(\x03R\rtotalRequests\x12 \n" +
	"\vtotalAmount\x18\x02 \x01(\x01R\vtotalAmount\"\x8b\x01\n" +
	"\x17PaymentsSummaryResponse\x126\n" +
	"\adefault\x18\x01 \x01(\v2\x1c.rinha_2025.ProcessorSummaryR\adefault\x128\n" +
	"\bfallback\x18\x02 \x01(\v2\x1c.rinha_2025.ProcessorSummaryR\bfallback2\xe2\x01\n" +
	"\x0ePaymentService\x12Y\n" +
	"\bPayments\x12\x1a.rinha_2025.PaymentRequest\x1a\x1b.rinha_2025.PaymentResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/payments\x12u\n" +
	"\x0fPaymentsSummary\x12\".rinha_2025.PaymentsSummaryRequest\x1a#.rinha_2025.PaymentsSummaryResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/payments-summaryB2Z0github.com/diogomassis/rinha-2025/internal/protob\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payment_proto_goTypes = []any{
	(*PaymentRequest)(nil),          // 0: rinha_2025.PaymentRequest
	(*PaymentResponse)(nil),         // 1: rinha_2025.PaymentResponse
	(*PaymentsSummaryRequest)(nil),  // 2: rinha_2025.PaymentsSummaryRequest
	(*ProcessorSummary)(nil),        // 3: rinha_2025.ProcessorSummary
	(*PaymentsSummaryResponse)(nil), // 4: rinha_2025.PaymentsSummaryResponse
}
var file_payment_proto_depIdxs = []int32{
	3, // 0: rinha_2025.PaymentsSummaryResponse.default:type_name -> rinha_2025.ProcessorSummary
	3, // 1: rinha_2025.PaymentsSummaryResponse.fallback:type_name -> rinha_2025.ProcessorSummary
	0, // 2: rinha_2025.PaymentService.Payments:input_type -> rinha_2025.PaymentRequest
	2, // 3: rinha_2025.PaymentService.PaymentsSummary:input_type -> rinha_2025.PaymentsSummaryRequest
	1, // 4: rinha_2025.PaymentService.Payments:output_type -> rinha_2025.PaymentResponse
	4, // 5: rinha_2025.PaymentService.PaymentsSummary:output_type -> rinha_2025.PaymentsSummaryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
