services:
  app1:
    image: rinha-2025
    environment:
      - INSTANCE_NAME=App-01
    depends_on:
      - redis
      - nats
    networks:
      - payment-processor
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  app2:
    image: rinha-2025
    environment:
      - INSTANCE_NAME=App-02
    depends_on:
      - redis
      - nats
    networks:
      - payment-processor
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  nats:
    image: nats:latest
    container_name: nats-server
    networks:
      - rinha-network
    restart: unless-stopped
    volumes:
      - ./nats-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  redis:
    image: "redis:latest"
    container_name: redis-server
    networks:
      - rinha-network
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge

volumes:
  redis-data:
  nats-data:
