services:
  load-balancer-nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  backend-1:
    image: rinha-2025
    environment:
      - PORT=8080
      - INSTANCE_NAME=backend-1
      - REDIS_ADDR=redis-server:6379
      - PAYMENT_DEFAULT_ENDPOINT=http://payment-processor-default:8080
      - PAYMENT_FALLBACK_ENDPOINT=http://payment-processor-fallback:8080
    depends_on:
      redis-server:
        condition: service_healthy
    networks:
      - payment-processor
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "120MB"
    restart: unless-stopped

  backend-2:
    image: rinha-2025
    environment:
      - PORT=8080
      - INSTANCE_NAME=backend-2
      - REDIS_ADDR=redis-server:6379
      - PAYMENT_DEFAULT_ENDPOINT=http://payment-processor-default:8080
      - PAYMENT_FALLBACK_ENDPOINT=http://payment-processor-fallback:8080
    depends_on:
      redis-server:
        condition: service_healthy
    networks:
      - payment-processor
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "120MB"
    restart: unless-stopped

  redis-server:
    image: "redis:latest"
    container_name: redis-server
    networks:
      - rinha-network
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command:
      - --maxmemory 70mb
      - --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "70MB"

networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge

volumes:
  redis-data:
