services:
  load-balancer-nginx:
    image: nginx:1.25.4-alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "35MB"

  backend-1:
    image: rinha-2025
    container_name: backend-1
    hostname: backend-1
    environment:
      - APP_PORT=8080
      - DB_URL=postgres://rinha:rinha@db:5432/rinha
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    restart: on-failure

  backend-2:
    image: rinha-2025
    container_name: backend-2
    hostname: backend-2
    environment:
      - APP_PORT=8080
      - DB_URL=postgres://rinha:rinha@db:5432/rinha
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    restart: on-failure

  db:
    image: postgres:16.2-alpine
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    # ports:
    #   - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "115MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha -q"]
      interval: 3s
      timeout: 2s
      retries: 10

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres-data:
