# Define o grupo de servidores para onde o tráfego será balanceado.
# app1 e app2 são os nomes dos serviços definidos no docker-compose.yml.
upstream rinha_backend {
    server app1:8080;
    server app2:8080;
}

server {
    # Nginx vai escutar na porta 80 dentro do contêiner.
    listen 80;

    location / {
        # Todas as requisições recebidas são passadas para o grupo definido acima.
        proxy_pass http://rinha_backend;
    }
}
