// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rinha.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_rinha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{0}
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_rinha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_rinha_proto protoreflect.FileDescriptor

const file_rinha_proto_rawDesc = "" +
	"\n" +
	"\vrinha.proto\x12\n" +
	"rinha_2025\x1a\x1cgoogle/api/annotations.proto\"\r\n" +
	"\vTestRequest\"&\n" +
	"\fTestResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2Z\n" +
	"\vTestService\x12K\n" +
	"\x04Test\x12\x17.rinha_2025.TestRequest\x1a\x18.rinha_2025.TestResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/testB)Z'github.com/diogomassis/rinha-2025/protob\x06proto3"

var (
	file_rinha_proto_rawDescOnce sync.Once
	file_rinha_proto_rawDescData []byte
)

func file_rinha_proto_rawDescGZIP() []byte {
	file_rinha_proto_rawDescOnce.Do(func() {
		file_rinha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rinha_proto_rawDesc), len(file_rinha_proto_rawDesc)))
	})
	return file_rinha_proto_rawDescData
}

var file_rinha_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rinha_proto_goTypes = []any{
	(*TestRequest)(nil),  // 0: rinha_2025.TestRequest
	(*TestResponse)(nil), // 1: rinha_2025.TestResponse
}
var file_rinha_proto_depIdxs = []int32{
	0, // 0: rinha_2025.TestService.Test:input_type -> rinha_2025.TestRequest
	1, // 1: rinha_2025.TestService.Test:output_type -> rinha_2025.TestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rinha_proto_init() }
func file_rinha_proto_init() {
	if File_rinha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rinha_proto_rawDesc), len(file_rinha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rinha_proto_goTypes,
		DependencyIndexes: file_rinha_proto_depIdxs,
		MessageInfos:      file_rinha_proto_msgTypes,
	}.Build()
	File_rinha_proto = out.File
	file_rinha_proto_goTypes = nil
	file_rinha_proto_depIdxs = nil
}
